#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v4
# autospec commit: 3d985eb
#
# Source0 file verified with key 0x02325448204E452A (carl@carlschwan.eu)
#
Name     : libqaccessibilityclient
Version  : 0.6.0
Release  : 3
URL      : https://download.kde.org/stable/libqaccessibilityclient/libqaccessibilityclient-0.6.0.tar.xz
Source0  : https://download.kde.org/stable/libqaccessibilityclient/libqaccessibilityclient-0.6.0.tar.xz
Source1  : https://download.kde.org/stable/libqaccessibilityclient/libqaccessibilityclient-0.6.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1 LGPL-3.0
Requires: libqaccessibilityclient-bin = %{version}-%{release}
Requires: libqaccessibilityclient-data = %{version}-%{release}
Requires: libqaccessibilityclient-lib = %{version}-%{release}
Requires: libqaccessibilityclient-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : buildreq-qt6
BuildRequires : extra-cmake-modules-data
BuildRequires : qtbase-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
To generate the documentation locally, just run:
$ doxygen doxygenconfig

%package bin
Summary: bin components for the libqaccessibilityclient package.
Group: Binaries
Requires: libqaccessibilityclient-data = %{version}-%{release}
Requires: libqaccessibilityclient-license = %{version}-%{release}

%description bin
bin components for the libqaccessibilityclient package.


%package data
Summary: data components for the libqaccessibilityclient package.
Group: Data

%description data
data components for the libqaccessibilityclient package.


%package dev
Summary: dev components for the libqaccessibilityclient package.
Group: Development
Requires: libqaccessibilityclient-lib = %{version}-%{release}
Requires: libqaccessibilityclient-bin = %{version}-%{release}
Requires: libqaccessibilityclient-data = %{version}-%{release}
Provides: libqaccessibilityclient-devel = %{version}-%{release}
Requires: libqaccessibilityclient = %{version}-%{release}

%description dev
dev components for the libqaccessibilityclient package.


%package lib
Summary: lib components for the libqaccessibilityclient package.
Group: Libraries
Requires: libqaccessibilityclient-data = %{version}-%{release}
Requires: libqaccessibilityclient-license = %{version}-%{release}

%description lib
lib components for the libqaccessibilityclient package.


%package license
Summary: license components for the libqaccessibilityclient package.
Group: Default

%description license
license components for the libqaccessibilityclient package.


%prep
%setup -q -n libqaccessibilityclient-0.6.0
cd %{_builddir}/libqaccessibilityclient-0.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1710340938
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DQT_MAJOR_VERSION=6
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1710340938
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libqaccessibilityclient
cp %{_builddir}/libqaccessibilityclient-%{version}/LICENSES/LGPL-2.1-only.txt %{buildroot}/usr/share/package-licenses/libqaccessibilityclient/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567 || :
cp %{_builddir}/libqaccessibilityclient-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/libqaccessibilityclient/19d98e1b6f8ef12849ea4012a052d3907f336c91 || :
cp %{_builddir}/libqaccessibilityclient-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/libqaccessibilityclient/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/libqaccessibilityclient-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/libqaccessibilityclient/e458941548e0864907e654fa2e192844ae90fc32 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dumper

%files data
%defattr(-,root,root,-)
/usr/share/qlogging-categories6/libqaccessibilityclient.categories

%files dev
%defattr(-,root,root,-)
/usr/include/QAccessibilityClient6/qaccessibilityclient/accessibleobject.h
/usr/include/QAccessibilityClient6/qaccessibilityclient/libqaccessibilityclient-version.h
/usr/include/QAccessibilityClient6/qaccessibilityclient/qaccessibilityclient_export.h
/usr/include/QAccessibilityClient6/qaccessibilityclient/registry.h
/usr/include/QAccessibilityClient6/qaccessibilityclient/registrycache_p.h
/usr/lib64/cmake/QAccessibilityClient6/QAccessibilityClient6Config.cmake
/usr/lib64/cmake/QAccessibilityClient6/QAccessibilityClient6ConfigVersion.cmake
/usr/lib64/cmake/QAccessibilityClient6/QAccessibilityClient6Targets-relwithdebinfo.cmake
/usr/lib64/cmake/QAccessibilityClient6/QAccessibilityClient6Targets.cmake
/usr/lib64/libqaccessibilityclient-qt6.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libqaccessibilityclient-qt6.so.0
/usr/lib64/libqaccessibilityclient-qt6.so.0.6.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libqaccessibilityclient/19d98e1b6f8ef12849ea4012a052d3907f336c91
/usr/share/package-licenses/libqaccessibilityclient/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567
/usr/share/package-licenses/libqaccessibilityclient/e458941548e0864907e654fa2e192844ae90fc32
